### ISSUE TITLE
Replace custom argparse/yaml arg handler with Hydra

### ISSUE THREAD

**Issue by Kaixhin** [SeanNobel/speech-decoding#26]
[Hydra](https://hydra.cc/) is:
1. Based on YAML config files (with arguments that can be overwritten on the command line)
2. Will let you compose configs so some hyperparameters can be shared across datasets
3. Automatically creates timestamped folders for experiment runs
4. Compatible with [W&B](https://docs.wandb.ai/guides/integrations/other/hydra)

Would replace `configs/args.py` (with some config moved into a "base" YAML config file) and `configs/parser.py`. No need to write experiment names or write into the `runs/` folder - Hydra will automatically make an `output` folder and put experiments in separate folders there.

**Comment by RomanKoshkin** [comment]
Implemented.
